---
name: Go Security Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Source
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'

      - name: Run Gosec Security Scanner
        uses: securego/gosec@2ae137abcf405533ad6e549e9363e58e4f6e8b7d # Update to go versions to 1.21.11 and 1.22.4
        with:
          args: './...'
